#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SlidingTabLayout.Resource", IsApplication=true)]

namespace SlidingTabLayout
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_overflow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int btnServer = 2131099651;
			
			// aapt resource value: 0x7f06000a
			public const int item_subtitle = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int item_title = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int menu = 2131099660;
			
			// aapt resource value: 0x7f060009
			public const int mylistviewmovie = 2131099657;
			
			// aapt resource value: 0x7f060005
			public const int sample_content_fragment = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int sample_main_layout = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int sliding_tabs = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int txtServerId = 2131099650;
			
			// aapt resource value: 0x7f060008
			public const int txtformat = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int txtlenght = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int txtmovie = 2131099654;
			
			// aapt resource value: 0x7f060001
			public const int viewpager = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int fragment_sapmle = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int layout_Server_config = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Movie_ListView_Row = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int MovieMainList = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int pager_item = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int actionbar_main = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
